# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20161122_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vtuurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
