# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_auto_20161122_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vtuurl',
            name='url',
            field=models.CharField(max_length=220, validators=[shortener.validators.validate_url, shortener.validators.validate_dot_com]),
        ),
    ]
