# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shortener', '0006_auto_20161125_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('vtu_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortener.VtuURL')),
            ],
        ),
    ]
